source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JTAppleCalendar_Example' do
  pod 'JTAppleCalendar', :path => '../'
end

target 'JTAppleCalendar_Tests' do
  pod 'JTAppleCalendar', :path => '../'

  
end
